openapi: 3.0.3
info:
  title: ''
  version: 0.0.0
paths:
  /api/schema/:
    get:
      operationId: api_schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - ckb
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - ms
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - ug
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - api
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
  /auth/login/:
    post:
      operationId: auth_login_create
      description: Login user and get JWT tokens
      tags:
      - auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLogin'
            examples:
              UserLoginExample:
                value:
                  username: john_doe
                  password: secure_password123
                summary: User Login Example
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UserLogin'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UserLogin'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                UserLoginExample:
                  value:
                    username: john_doe
                    password: secure_password123
                  summary: User Login Example
          description: ''
  /auth/profile/:
    get:
      operationId: auth_profile_retrieve
      description: Get current user profile information
      tags:
      - auth
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
  /auth/refresh/:
    post:
      operationId: auth_refresh_create
      description: |-
        Takes a refresh type JSON web token and returns an access type JSON web
        token if the refresh token is valid.
      tags:
      - auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenRefresh'
          description: ''
  /auth/register/:
    post:
      operationId: auth_register_create
      description: Register a new user account
      tags:
      - auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegistration'
            examples:
              UserRegistrationExample:
                value:
                  username: john_doe
                  email: john@example.com
                  first_name: John
                  last_name: Doe
                  password: secure_password123
                  password_confirm: secure_password123
                summary: User Registration Example
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UserRegistration'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UserRegistration'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                UserRegistrationExample:
                  value:
                    username: john_doe
                    email: john@example.com
                    first_name: John
                    last_name: Doe
                    password: secure_password123
                    password_confirm: secure_password123
                  summary: User Registration Example
          description: ''
  /dashboard/bookings/:
    get:
      operationId: dashboard_bookings_retrieve
      description: Get all bookings for dashboard management
      summary: Dashboard Bookings
      tags:
      - dashboard
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /dashboard/projects/:
    get:
      operationId: dashboard_projects_retrieve
      description: Get all projects with plot statistics for dashboard
      summary: Dashboard Projects
      tags:
      - dashboard
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /dashboard/recent-activity/:
    get:
      operationId: dashboard_recent_activity_retrieve
      description: Get recent bookings and projects activity for dashboard
      summary: Dashboard Recent Activity
      tags:
      - dashboard
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /dashboard/stats/:
    get:
      operationId: dashboard_stats_retrieve
      description: Get dashboard statistics including total projects, plots, bookings
        and revenue
      summary: Dashboard Statistics
      tags:
      - dashboard
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /land/create_booking/:
    get:
      operationId: land_create_booking_retrieve
      tags:
      - land
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Booking'
          description: ''
    post:
      operationId: land_create_booking_create
      tags:
      - land
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Booking'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Booking'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Booking'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Booking'
          description: ''
  /land/create_project/:
    get:
      operationId: land_create_project_retrieve
      tags:
      - land
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
          description: ''
    post:
      operationId: land_create_project_create
      tags:
      - land
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Project'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Project'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Project'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
          description: ''
  /land/plots/:
    get:
      operationId: land_plots_retrieve
      tags:
      - land
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Plots'
          description: ''
    post:
      operationId: land_plots_create
      tags:
      - land
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Plots'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Plots'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Plots'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Plots'
          description: ''
components:
  schemas:
    Booking:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        customer_name:
          type: string
          maxLength: 200
        customer_contact:
          type: string
          maxLength: 100
        booking_date:
          type: string
          format: date-time
          readOnly: true
        payment_reference:
          type: string
          maxLength: 100
        payment_method:
          $ref: '#/components/schemas/PaymentMethodEnum'
        amount_paid:
          type: string
          format: decimal
          pattern: ^-?\d{0,13}(?:\.\d{0,2})?$
        status:
          $ref: '#/components/schemas/StatusEnum'
        plot:
          type: integer
      required:
      - amount_paid
      - booking_date
      - customer_contact
      - customer_name
      - id
      - payment_method
      - payment_reference
      - plot
      - status
    PaymentMethodEnum:
      enum:
      - cash
      - mpesa
      - bank_transfer
      type: string
      description: |-
        * `cash` - Cash
        * `mpesa` - mpesa
        * `bank_transfer` - Bank Transfer
    Plots:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        plot_number:
          type: string
          maxLength: 50
        size:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
        price:
          type: string
          format: decimal
          pattern: ^-?\d{0,13}(?:\.\d{0,2})?$
        is_available:
          type: boolean
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
        project:
          type: integer
      required:
      - created_at
      - id
      - plot_number
      - price
      - project
      - size
      - updated_at
    Project:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 200
        phase:
          type: array
          items:
            type: string
            maxLength: 100
        project_svg_map:
          type: string
          format: uri
          nullable: true
        location:
          type: string
          maxLength: 300
        size:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
      required:
      - created_at
      - id
      - location
      - name
      - size
      - updated_at
    PropertyTypeEnum:
      enum:
      - commercial
      - residential
      type: string
      description: |-
        * `commercial` - Commercial
        * `residential` - Residential
    StatusEnum:
      enum:
      - booked
      - confirmed
      - cancelled
      type: string
      description: |-
        * `booked` - Booked
        * `confirmed` - Confirmed
        * `cancelled` - Cancelled
    TokenRefresh:
      type: object
      properties:
        access:
          type: string
          readOnly: true
        refresh:
          type: string
      required:
      - access
      - refresh
    User:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        username:
          type: string
          description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_
            only.
          pattern: ^[\w.@+-]+$
          maxLength: 150
        email:
          type: string
          format: email
          title: Email address
          maxLength: 254
        first_name:
          type: string
          maxLength: 150
        last_name:
          type: string
          maxLength: 150
        is_active:
          type: boolean
          title: Active
          description: Designates whether this user should be treated as active. Unselect
            this instead of deleting accounts.
        date_joined:
          type: string
          format: date-time
          readOnly: true
      required:
      - date_joined
      - id
      - username
    UserLogin:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
      - password
      - username
    UserRegistration:
      type: object
      properties:
        username:
          type: string
          description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_
            only.
          pattern: ^[\w.@+-]+$
          maxLength: 150
        email:
          type: string
          format: email
          title: Email address
          maxLength: 254
        first_name:
          type: string
          maxLength: 150
        last_name:
          type: string
          maxLength: 150
        password:
          type: string
          writeOnly: true
          minLength: 8
        password_confirm:
          type: string
          writeOnly: true
      required:
      - password
      - password_confirm
      - username
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
