# Generated by Django 5.2.3 on 2026-02-01 19:04

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('template_type', models.CharField(choices=[('welcome', 'Welcome Email'), ('password_reset', 'Password Reset'), ('subscription_success', 'Subscription Success'), ('subscription_expiring', 'Subscription Expiring'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('custom', 'Custom Template')], max_length=50, unique=True)),
                ('subject', models.CharField(max_length=500)),
                ('body_html', models.TextField(help_text='HTML body with {{variable}} placeholders')),
                ('body_text', models.TextField(help_text='Plain text fallback')),
                ('available_variables', models.JSONField(default=list, help_text="List of available variables: ['user_name', 'amount', etc.]")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdminRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(choices=[('super_admin', 'Super Admin'), ('content_admin', 'Content Admin'), ('finance_admin', 'Finance Admin'), ('support_admin', 'Support Admin')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('can_access_dashboard', models.BooleanField(default=True)),
                ('can_export_data', models.BooleanField(default=False)),
                ('can_view_audit_logs', models.BooleanField(default=False)),
                ('api_rate_limit', models.IntegerField(default=1000, help_text='API calls per hour')),
                ('accessible_modules', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='List of modules: users, projects, plots, bookings, sales, payments, subscriptions, settings', size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_role', to='auth.group')),
            ],
            options={
                'ordering': ['role_type'],
            },
        ),
        migrations.CreateModel(
            name='UserAdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin_active', models.BooleanField(default=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('last_admin_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('roles', models.ManyToManyField(blank=True, related_name='users', to='super_admin.adminrole')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Snapshot of username', max_length=150)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('action', models.CharField(choices=[('create', 'Create'), ('read', 'Read'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('export', 'Export'), ('bulk_operation', 'Bulk Operation'), ('settings_change', 'Settings Change'), ('role_change', 'Role Change')], max_length=50)),
                ('resource_type', models.CharField(choices=[('user', 'User'), ('project', 'Project'), ('plot', 'Plot'), ('booking', 'Booking'), ('sale', 'Sale'), ('payment', 'Payment'), ('subscription', 'Subscription'), ('subscription_plan', 'Subscription Plan'), ('system_setting', 'System Setting'), ('admin_role', 'Admin Role')], max_length=50)),
                ('resource_id', models.CharField(blank=True, help_text='ID of affected resource', max_length=100)),
                ('description', models.TextField(help_text='Human-readable description')),
                ('changes', models.JSONField(blank=True, default=dict, help_text="Before/after values: {field: {old: '', new: ''}}")),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context data')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('was_successful', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='super_admin_user_id_6ed676_idx'), models.Index(fields=['action', 'timestamp'], name='super_admin_action_ffca57_idx'), models.Index(fields=['resource_type', 'resource_id'], name='super_admin_resourc_8ace25_idx'), models.Index(fields=['timestamp'], name='super_admin_timesta_1de4c6_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=200, unique=True)),
                ('value', models.TextField()),
                ('setting_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('float', 'Float'), ('boolean', 'Boolean'), ('json', 'JSON'), ('email', 'Email'), ('url', 'URL')], default='string', max_length=20)),
                ('category', models.CharField(choices=[('general', 'General'), ('email', 'Email Configuration'), ('payment', 'Payment Settings'), ('features', 'Feature Flags'), ('security', 'Security'), ('notifications', 'Notifications'), ('api', 'API Configuration')], default='general', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Description of this setting')),
                ('is_public', models.BooleanField(default=False, help_text='Can non-admin users read this?')),
                ('is_editable', models.BooleanField(default=True, help_text='Can this be edited via API?')),
                ('validation_rules', models.JSONField(blank=True, default=dict, help_text="JSON rules: {min: 0, max: 100, regex: '...', choices: []}")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'key'],
                'indexes': [models.Index(fields=['category'], name='super_admin_categor_4e10d2_idx'), models.Index(fields=['key'], name='super_admin_key_7ea947_idx')],
            },
        ),
    ]
