# Generated by Django 5.2.3 on 2026-02-01 19:05

from django.db import migrations


def create_default_roles(apps, schema_editor):
    """
    Create default admin roles with appropriate permissions and settings
    """
    AdminRole = apps.get_model('super_admin', 'AdminRole')
    Group = apps.get_model('auth', 'Group')

    # Define default roles configuration
    roles_config = [
        {
            'role_type': 'super_admin',
            'group_name': 'Super Administrators',
            'description': 'Full system access - can manage everything including settings and roles',
            'can_access_dashboard': True,
            'can_export_data': True,
            'can_view_audit_logs': True,
            'api_rate_limit': 10000,
            'accessible_modules': ['users', 'projects', 'plots', 'bookings', 'sales', 'payments', 'subscriptions', 'settings', 'roles', 'audit_logs'],
        },
        {
            'role_type': 'content_admin',
            'group_name': 'Content Administrators',
            'description': 'Manage projects, plots, and bookings - no access to finance or system settings',
            'can_access_dashboard': True,
            'can_export_data': True,
            'can_view_audit_logs': False,
            'api_rate_limit': 5000,
            'accessible_modules': ['users', 'projects', 'plots', 'bookings'],
        },
        {
            'role_type': 'finance_admin',
            'group_name': 'Finance Administrators',
            'description': 'Manage payments, subscriptions, and plans - no access to content or settings',
            'can_access_dashboard': True,
            'can_export_data': True,
            'can_view_audit_logs': False,
            'api_rate_limit': 5000,
            'accessible_modules': ['users', 'payments', 'subscriptions', 'sales'],
        },
        {
            'role_type': 'support_admin',
            'group_name': 'Support Team',
            'description': 'Read-only access to most resources with limited actions',
            'can_access_dashboard': True,
            'can_export_data': False,
            'can_view_audit_logs': True,
            'api_rate_limit': 2000,
            'accessible_modules': ['users', 'projects', 'plots', 'bookings', 'sales', 'payments', 'subscriptions'],
        },
    ]

    # Create each role
    for config in roles_config:
        # Create or get the Group
        group, created = Group.objects.get_or_create(name=config['group_name'])

        # Create the AdminRole
        admin_role, created = AdminRole.objects.get_or_create(
            role_type=config['role_type'],
            defaults={
                'group': group,
                'description': config['description'],
                'can_access_dashboard': config['can_access_dashboard'],
                'can_export_data': config['can_export_data'],
                'can_view_audit_logs': config['can_view_audit_logs'],
                'api_rate_limit': config['api_rate_limit'],
                'accessible_modules': config['accessible_modules'],
            }
        )


def remove_default_roles(apps, schema_editor):
    """
    Reverse migration - remove default roles
    """
    AdminRole = apps.get_model('super_admin', 'AdminRole')
    Group = apps.get_model('auth', 'Group')

    # Remove roles
    role_types = ['super_admin', 'content_admin', 'finance_admin', 'support_admin']
    for role_type in role_types:
        try:
            role = AdminRole.objects.get(role_type=role_type)
            group = role.group
            role.delete()
            group.delete()
        except AdminRole.DoesNotExist:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),  # Ensure auth app migrations are applied
    ]

    operations = [
        migrations.RunPython(create_default_roles, remove_default_roles),
    ]
