# Generated by Django 5.2.3 on 2026-01-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_subscriptionplan_usersubscription_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='flutterwave_transaction_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='flutterwave_tx_ref',
        ),
        migrations.AddField(
            model_name='payment',
            name='is_recurring',
            field=models.BooleanField(default=False, help_text='Whether this is a recurring payment setup'),
        ),
        migrations.AddField(
            model_name='payment',
            name='pesapal_merchant_reference',
            field=models.CharField(blank=True, help_text='Our internal reference', max_length=200),
        ),
        migrations.AddField(
            model_name='payment',
            name='pesapal_order_tracking_id',
            field=models.CharField(blank=True, help_text='Pesapal OrderTrackingId', max_length=200),
        ),
        migrations.AddField(
            model_name='payment',
            name='pesapal_transaction_id',
            field=models.CharField(blank=True, help_text='Pesapal transaction ID after completion', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='recurring_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='recurring_frequency',
            field=models.CharField(blank=True, choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='recurring_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='last_recurring_payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='recurring_payment_active',
            field=models.BooleanField(default=False, help_text='Whether user has active recurring payment configured at Pesapal'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='KES', max_length=10),
        ),
    ]
