# Generated by Django 5.2.9 on 2026-02-21 19:21

from django.db import migrations


def populate_user_profiles(apps, schema_editor):
    """
    Create UserProfile for all existing users based on their current status
    - Superusers → 'super_admin'
    - Users with projects → 'admin'
    - Others → 'client'
    """
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('authentication', 'UserProfile')
    Project = apps.get_model('land', 'Project')

    for user in User.objects.all():
        # Skip if profile already exists
        if UserProfile.objects.filter(user=user).exists():
            continue

        # Determine user type
        if user.is_superuser:
            user_type = 'super_admin'
        elif Project.objects.filter(user=user).exists():
            user_type = 'admin'  # Has projects = is admin
        else:
            user_type = 'client'

        # Create UserProfile
        UserProfile.objects.create(
            user=user,
            user_type=user_type,
            is_active=True
        )


def reverse_populate(apps, schema_editor):
    """Delete all UserProfiles"""
    UserProfile = apps.get_model('authentication', 'UserProfile')
    UserProfile.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_userprofile'),
        ('land', '0013_booking_user_alter_booking_customer_contact_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_user_profiles, reverse_populate),
    ]
