# Generated by Django 5.2.9 on 2025-12-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_numbber', models.IntegerField()),
                ('size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('property_type', models.CharField(choices=[('commercial', 'Commercial'), ('residential', 'Residential')], max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
    ]
