# Generated by Django 5.2.9 on 2025-12-03 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='land',
            old_name='plot_numbber',
            new_name='plot_number',
        ),
    ]
