# Generated by Django 5.2.3 on 2025-12-18 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0002_rename_plot_numbber_land_plot_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_contact', models.CharField(max_length=100)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('payment_reference', models.CharField(max_length=100)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'mpesa'), ('bank_transfer', 'Bank Transfer')], max_length=100)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Plots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_number', models.CharField(max_length=50)),
                ('size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phase', models.CharField(max_length=100)),
                ('project_svg_map', models.FileField(upload_to='project_maps/')),
                ('location', models.CharField(max_length=300)),
                ('size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('property_type', models.CharField(choices=[('commercial', 'Commercial'), ('residential', 'Residential')], max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Land',
        ),
        migrations.AddField(
            model_name='booking',
            name='plot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='land.plots'),
        ),
        migrations.AddField(
            model_name='plots',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='land.project'),
        ),
    ]
