# Generated by Django 5.2.3 on 2026-01-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0003_booking_plots_project_delete_land_booking_plot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_svg_map',
            field=models.FileField(blank=True, null=True, upload_to='project_maps/'),
        ),
    ]
