# Generated by Django 5.2.3 on 2026-01-07 20:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0005_transform_phase_to_array'),
    ]

    operations = [
        migrations.AddField(
            model_name='plots',
            name='phase',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='plots',
            name='property_type',
            field=models.CharField(choices=[('commercial', 'Commercial'), ('residential', 'Residential')], default='residential', max_length=100),
        ),
    ]
