# Generated by Django 5.2.3 on 2026-01-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0006_plots_phase_plots_property_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
