# Generated by Django 5.2.3 on 2026-01-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0007_booking_purchase_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='phase',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
