# Generated by Django 5.2.3 on 2026-01-28 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0008_booking_phase'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(max_length=100)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('commission', models.DecimalField(decimal_places=2, max_digits=15)),
                ('sub_agent', models.BooleanField(default=False)),
                ('sub_agent_name', models.CharField(blank=True, default='', max_length=200)),
                ('principal_agent', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='land.plots')),
            ],
            options={
                'verbose_name_plural': 'Agent Sales',
            },
        ),
        migrations.CreateModel(
            name='ProjectSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=200)),
                ('phase', models.CharField(max_length=100)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='land.plots')),
            ],
            options={
                'verbose_name_plural': 'Project Sales',
            },
        ),
    ]
