# Generated by Django 5.2.3 on 2026-01-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0009_agentsales_projectsales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentsales',
            name='sub_agent',
        ),
        migrations.AlterField(
            model_name='agentsales',
            name='commission',
            field=models.DecimalField(decimal_places=2, help_text='Commission percentage (e.g., 5.00 for 5%)', max_digits=5),
        ),
    ]
