# Generated by Django 5.2.3 on 2026-02-12 20:33

from django.db import migrations, models


def clear_old_file_paths(apps, schema_editor):
    """
    Clear old file paths since we're switching to base64 storage.
    Users will need to re-upload their maps.
    """
    Project = apps.get_model('land', 'Project')
    Project.objects.all().update(project_svg_map=None)


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0011_project_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_svg_map',
            field=models.TextField(blank=True, help_text='Base64 encoded image data URL (e.g., data:image/svg+xml;base64,...)', null=True),
        ),
        migrations.RunPython(clear_old_file_paths, reverse_code=migrations.RunPython.noop),
    ]
