# Generated by Django 5.2.9 on 2026-02-21 19:21

from django.db import migrations


def populate_booking_users(apps, schema_editor):
    """
    Set booking.user to plot.project.user for all existing bookings
    Also populate customer_name and customer_contact from user if empty
    """
    Booking = apps.get_model('land', 'Booking')

    for booking in Booking.objects.filter(user__isnull=True):
        # Set user to project owner
        if booking.plot and booking.plot.project and booking.plot.project.user:
            booking.user = booking.plot.project.user

            # Populate customer_name if empty
            if not booking.customer_name:
                user = booking.user
                booking.customer_name = user.get_full_name() or user.username

            booking.save()


def reverse_populate(apps, schema_editor):
    """Set all booking.user back to null"""
    Booking = apps.get_model('land', 'Booking')
    Booking.objects.all().update(user=None)


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0013_booking_user_alter_booking_customer_contact_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_booking_users, reverse_populate),
    ]
