# Generated by Django 5.2.9 on 2026-02-21 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0014_populate_booking_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(
                help_text='User (client/subagent/admin) who made this booking',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='bookings',
                to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
